angular.module('kityminderEditor')
    .service('lang.en', function() {
        return {
            'template': {
                'default': 'Mind map',
                'tianpan': 'Sky map',
                'structure': 'Organization Chart',
                'filetree': 'Directory organization chart',
                'right': 'logical structure diagram',
                'fish-bone': 'Fish bone figure'
            },
            'theme': {
                'classic': 'The mind map classic',
                'classic-compact': 'Compact classic',
                'snow': 'Gentle cold light',
                'snow-compact': 'Compact cold light',
                'fish': 'Fish bone map',
                'wire': 'Wireframe',
                'fresh-red': 'Fresh red',
                'fresh-soil': 'Dirty yellow',
                'fresh-green': 'Artistic Green',
                'fresh-blue': 'Sky Blue',
                'fresh-purple': 'Romantic Purple',
                'fresh-pink': 'Mind powder',
                'fresh-red-compat': 'Compact red',
                'fresh-soil-compat': 'Compact yellow',
                'fresh-green-compat': 'Compact green',
                'fresh-blue-compat': 'Compact blue',
                'fresh-purple-compat': 'Compact purple',
                'fresh-pink-compat': 'Compact powder',
                'tianpan': 'Classic dial',
                'tianpan-compact': 'Compact day'
            },
            'maintopic': 'Center theme',
            'topic': 'branch topic',
            'panels': {
                'history': 'history',
                'template': 'template',
                'theme': 'skin',
                'layout': 'layout',
                'style': 'style',
                'font': 'text',
                'color': 'color',
                'background': 'background',
                'insert': 'insert',
                'arrange': 'adjust',
                'nodeop': 'current',
                'priority': 'priority',
                'progress': 'progress',
                'resource': 'resource',
                'note': 'note',
                'attachment': 'attachment',
                'word': 'text'
            },
            'ui': {
                'command': {
                    'appendsiblingnode': 'Insert sibling node',
                    'appendparentnode': 'Insert parent node below',
                    'appendchildnode': 'Insert child node',
                    'removenode': 'Del',
                    'editnode': 'Edit',
                    'arrangeup': 'Up',
                    'arrangedown': 'Down',
                    'resetlayout': 'Organize layout',
                    'expandtoleaf': 'Expand all nodes',
                    'expandtolevel1': 'Expand to level 1',
                    'expandtolevel2': 'Expand to level 2',
                    'expandtolevel3': 'Expand to level 3',
                    'expandtolevel4': 'Expand to level 4',
                    'expandtolevel5': 'Expand to level 5',
                    'expandtolevel6': 'Expand to level 6',
                    'fullscreen': 'full screen',
                    'outline': 'outline'
                },
                'search': 'search',
                'export': 'export',
                'expandtoleaf': 'expand',
                'back': 'return',
                'undo': 'Undo (Ctrl + Z)',
                'redo': 'Redo (Ctrl + Y)',
                'tabs': {
                    'idea': 'Format',
                    'appearence': 'Appearance',
                    'view': 'View'
                },
                'bold': 'Bold',
                'italic': 'italic',
                'forecolor': 'font color',
                'fontfamily': 'font',
                'fontsize': 'font size',
                'layoutstyle': 'theme',
                'node': 'node operation',
                'hand': 'Allow dragging',
                'camera': 'Locate the root node',
                'zoom-in': 'Zoom in (Ctrl+)',
                'zoom-out': 'Zoom out (Ctrl-)',
                'markers': 'tag',
                'resource': 'resource',
                'help': 'Help',
                'preference': 'Preferences',
                'expandnode': 'Expand to leaf',
                'collapsenode': 'receive a level one node',
                'template': 'template',
                'theme': 'skin',
                'clearstyle': 'clear style',
                'copystyle': 'copy style',
                'pastestyle': 'paste style',
                'appendsiblingnode': 'same theme',
                'appendchildnode': 'subordinate theme',
                'arrangeup': 'pre-tune',
                'arrangedown': 'post-tune',
                'editnode': 'Edit',
                'removenode': 'remove',
                'priority': 'Priority',
                'progress': {
                    'p1': 'not started',
                    'p2': 'Complete 1/8',
                    'p3': 'Complete 1/4',
                    'p4': 'Complete 3/8',
                    'p5': 'Complete half',
                    'p6': 'Complete 5/8',
                    'p7': 'Complete 3/4',
                    'p8': 'Complete 7/8',
                    'p9': 'Completed',
                    'p0': 'clear progress'
                },
                'link': 'link',
                'image': 'picture',
                'note': 'Remarks',
                'insertlink': 'insert link',
                'insertimage': 'insert image',
                'insertnote': 'insert note',
                'removelink': 'Remove existing links',
                'removeimage': 'Remove existing image',
                'removenote': 'Remove existing notes',
                'resetlayout': 'Organize',
                'navigator': 'navigator',
                'selectall': 'Select all',
                'selectrevert': 'inverse selection',
                'selectsiblings': 'Select sibling nodes',
                'selectlevel': 'All nodes on the same level',
                'selectpath': 'Select path',
                'selecttree': 'Select subtree'
            },
            'popupcolor': {
                'clearColor': 'clear color',
                'standardColor': 'standard color',
                'themeColor': 'Theme color'
            },
            'hyperlink': {
                'hyperlink': 'link...',
                'unhyperlink': 'Remove link'
            },
            'image': {
                'image': 'image...',
                'removeimage': 'Remove image'
            },
            'marker': {
                'marker': 'progress/priority...'
            },
            'resource': {
                'resource': 'Resources...'
            }
        };
    });